server:
  port: 8080
  enable_pprof: true
  log_level: debug

mysql:
  user: root
  password: 123456 #自己的mysql数据库密码
  host: localhost
  port: 3306
  database: goshow_mall
  charset: utf8mb4
  show_sql: true
  max_open_conn: 10
  max_idle_conn: 5

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  max_open: 10
  max_idle: 2

app_config: #app配置
  1002: #app配置对象的id
    app_type: #app唯一编号
    app_name: #app名
    app_id: #appid
    app_secret: #app密钥